### ISSUE TITLE
自动化部署时报错：Command not found

### ISSUE THREAD

**Issue by 363797271** [lagoufed/fed-e-001#4]
## 正在学习的内容

NuxtJS开发的SSR应用，使用 GitHub Actions +Linux服务器 实现自动化部署

## 遇到的问题

Linux服务器手动连接后按照传统部署步骤，执行 npm pm2 命令正常，但是GitHub Actions 中使用同账户（root）连接后，执行这些命令就报错：Command not fount

## 重现步骤

自己从阿里云购买的云服务器ECS，使用root账号登录。
按照[nvm官方教程](https://github.com/nvm-sh/nvm)安装了nvm：
```shell
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```
然后安装了node：
```shell
nvm install 12.17.0
nvm use 12.17.0
```
之后全局安装了 pm2，并安装了tar工具。
按照课程中传统部署方式，应用发布成功，一切正常。
可是在GitHub Actions 中，就找不到 npm pm2 命令。

经过反复测试发现（以下是 GitHub Actions中打印结果）：

- `whereis node` 结果是空的
- `echo $PATH` 结果是初始值，没有配置node路径
- `cd` + `ls -a` 文件目录都存在，一直可以看到 `/root/.nvm/versions/node/v12.17.0/bin`，npm pm2 都存在

## 我做的努力

- 首先根据网上介绍的，在`/root/.bashrc`中添加环境变量配置
  - 底部添加 `export PATH=/root/.nvm/versions/node/v12.17.0/bin:$PATH`
  - 执行命令使其生效`source /root/.bashrc`
  - 结果不成功
- 然后同样方法修改 `/etc/profile`
  - 结果也不成功

以上结果都重启了服务器。

## 最终解决办法

最终在 `./github/workflows/main.yml` 配置文件中执行的命令前添加了环境变量配置，才发布成功。

```yaml
#...
script: |
  export PATH=/root/.nvm/versions/node/v12.17.0/bin:$PATH
  cd /root/realworld-nuxtjs
#...
```

**到现在没有找到问题根源，请老师帮忙解答！**

附上main.yml：

```yaml
name: Publish And Deploy Demo
on:
  push:
    # 提交tag名以v开头的tag时执行部署任务
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 执行的步骤
    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@master

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      # 生成压缩包（打包 .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json）
      - run: tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json

      # 发布 Release（创建Release分支）
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          # 本次提交的tag的名称
          tag_name: ${{ github.ref }}
          # Release版本的名称
          release_name: Release ${{ github.ref }}
          # 是否是草稿
          draft: false
          # 是否是预发布
          prerelease: false

      # 上传构建结果（release.tgz）到 Release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          # 上传地址（创建的Release分支地址）
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 上传的文件
          asset_path: ./release.tgz
          # 上传后的文件名
          asset_name: release.tgz
          # 上传的文件类型
          asset_content_type: application/x-tgz

      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          # 远程服务器地址
          host: ${{ secrets.HOST }}
          # 远程服务器用户名
          username: ${{ secrets.USERNAME }}
          # 远程服务器密码
          password: ${{ secrets.PASSWORD }}
          # 远程服务器端口号
          port: ${{ secrets.PORT }}
          # 命令超时配置
          command_timeout: 20m
          # 运行在远程服务器的命令
          # 0. 手动添加环境变量（此任务中PATH环境变量一直是初始值，没找到原因）
          # 1. 进入项目目录
          # 2. 下载发布包
          # 3. 解压缩发布包
          # 4. 安装生产环境依赖
          # 5. pm2运行配置文件
          script: |
            export PATH=/root/.nvm/versions/node/v12.17.0/bin:$PATH
            cd /root/realworld-nuxtjs
            wget https://github.com/363797271/realworld-nuxtjs/releases/latest/download/release.tgz -O release.tgz
            tar zxvf release.tgz
            npm install --production
            pm2 reload pm2.config.json
```
